// counter types
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

// Auth types
export const LOAD_USER = 'LOAD_USER';
export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const AUTH_ERROR = 'AUTH_ERROR';

// Post types
export const GET_POSTS = 'GET_POSTS';
export const CREATE_POST = 'CREATE_POST';
export const GET_POST_BY_ID = 'GET_POST_BY_ID';
export const DELETE_POST_BY_ID = 'DELETE_POST_BY_ID';
export const UPDATE_POST_BY_ID = 'UPDATE_POST_BY_ID';
export const POST_ERROR = 'POST_ERROR';
export const CREATE_POST_COMMENT_BY_POST_ID = 'CREATE_POST_COMMENT_BY_POST_ID';
export const GET_POST_COMMENTS_BY_POST_ID = 'GET_POST_COMMENTS_BY_POST_ID';
export const DELETE_POST_COMMENT_BY_POST_ID = 'DELETE_POST_COMMENT_BY_POST_ID';

// Study types
export const GET_STUDIES = 'GET_STUDIES';
export const CREATE_STUDY = 'CREATE_STUDY';
export const GET_STUDY_BY_ID = 'GET_STUDY_BY_ID';
export const DELETE_STUDY_BY_ID = 'DELETE_STUDY_BY_ID';
export const UPDATE_STUDY_BY_ID = 'UPDATE_STUDY_BY_ID';
export const JOIN_STUDY_BY_ID = 'JOIN_STUDY_BY_ID';
export const STUDY_ERROR = 'POST_ERROR';

// Study Todo types
export const GET_STUDY_TODOS_BY_STUDY_ID = 'GET_STUDY_TODOS_BY_STUDY_ID';
export const CREATE_STUDY_TODO_BY_STUDY_ID = 'CREATE_STUDY_TODO_BY_STUDY_ID';
export const UPDATE_STUDY_TODO_BY_STUDY_ID = 'UPDATE_STUDY_TODO_BY_STUDY_ID';
export const DELETE_STUDY_TODO_BY_STUDY_ID = 'DELETE_STUDY_TODO_BY_STUDY_ID';
export const STUDY_TODO_ERROR = 'STUDY_TODO_ERROR';
